#!/bin/sh -e

install -Dm644 ./Mukta-Devanagari/*.ttf -t"$1/usr/share/fonts/mukta/"
install -Dm644 ./MuktaMahee-Gurmukhi/*.ttf -t "$1/usr/share/fonts/mukta/"
install -Dm644 ./MuktaMalar-Tamil/*.ttf -t "$1/usr/share/fonts/mukta/"
install -Dm644 ./MuktaVaani-Gujarati/*.ttf -t "$1/usr/share/fonts/mukta/"
