#!/bin/sh -e

ls
install -Dm644 ./SourceHanSansCN/*.otf -t "$1/usr/share/fonts/OTF/"
install -Dm644 ./SourceHanSansHK/*.otf -t "$1/usr/share/fonts/OTF/"
install -Dm644 ./SourceHanSansJP/*.otf -t "$1/usr/share/fonts/OTF/"
install -Dm644 ./SourceHanSansKR/*.otf -t "$1/usr/share/fonts/OTF/"
install -Dm644 ./SourceHanSansTW/*.otf -t "$1/usr/share/fonts/OTF/"
